---
- name: Run playbook
  gather_facts: false
  hosts: server
  roles:
    - basic
    - security
    - wireguard_server
    - web
    - api
    - squid
    - dns
  tasks:
    - name: Import wireguard_middleman role for middleman server
      ansible.builtin.include_role:
        name: wireguard_middleman
      when: inventory_hostname == 'wireguard_middleman'
