---
- name: Run playbook
  gather_facts: false
  hosts: main_server
  roles:
    - basic
    - security
    - wireguard_server
    - web
    - api
    - squid
    - dns
    # - wireguard_middleman

- name: Run playbook
  gather_facts: false
  hosts: routing_server
  roles:
    - basic
    - security
    - wireguard_server
    - web
    - api
    - squid
    - dns
    - wireguard_middleman
