---
wireguard_server__out_interface: ens3
wireguard_server__ipv4_network: 172.16.0.0/16
wireguard_server__ipv6_network: fd01:9067:7d3a:e4da::/64
wireguard_server__ipv4: 172.16.0.1/16
wireguard_server__ipv6: fd01:9067:7d3a:e4da::1/64
wireguard_server__psk_save_path: /var/wireguard/psk
