---
server:
  vars:
    ansible_user: root
    ansible_web_user: kurtn3x
    ansible_private_user: kurtn3x
  hosts:
    kurtn3x:
      ansible_host: 193.218.118.220
    wireguard_middleman:
      ansible_host: 85.235.66.68
