---
- name: Install basic packages
  ansible.builtin.apt:
    name:
      - python3.11
      - python3.11-venv
      - vim
      - sudo
      - curl
      - git
    update_cache: yes

- name: Add private user
  ansible.builtin.user:
    name: "{{ ansible_private_user }}"
    shell: /bin/bash
    groups: sudo
    append: yes

- name: Make root use bash
  ansible.builtin.user:
    name: root
    shell: /bin/bash
    