---
- name: Install unbound & ufw
  ansible.builtin.apt:
    update_cache: true
    name:
      - unbound
      - ufw

- name: Generate unbound.conf
  ansible.builtin.template:
    src: templates/unbound.conf.j2
    dest: /etc/unbound/unbound.conf
    owner: root
    group: root
    mode: "0644"

- name: Copy unbound blocklist script
  ansible.builtin.copy:
    src: files/gen_blocklist.sh
    dest: /etc/unbound/gen_blocklist.sh
    owner: root
    group: root
    mode: "0755"

- name: Create cronjob for unbound blocklist script
  ansible.builtin.cron:
    name: "Run unbound blocklist script"
    special_time: weekly
    job: "/etc/unbound/gen_blocklist.sh"

- name: Enable and start unbound
  ansible.builtin.systemd_service:
    name: unbound
    state: started
    enabled: true

- name: Set Firewall rules
  block:
    - name: Allow ssh (22)
      community.general.ufw:
        rule: allow
        port: 22

    - name: Allow dns (53) on wg0
      community.general.ufw:
        rule: allow
        port: 53
        interface_in: wg0

    - name: Enable Firewall and block traffic by default
      community.general.ufw:
        default: reject
        state: enabled

    - name: Enable and start ufw
      ansible.builtin.service:
        name: ufw
        state: started
        enabled: true
