---
- name: Install nginx, git & ufw
  ansible.builtin.apt:
    update_cache: true
    name:
      - nginx
      - git
      - ufw

- name: Copy nginx configs
  ansible.builtin.copy:
    src: "files/nginx/"
    dest: "/etc/nginx/"
    owner: root
    group: root
    mode: "0644"

- name: Get copied sites
  ansible.builtin.command: "ls /etc/nginx/sites-available"
  changed_when: false
  register: sites

- name: Create a symbolic links for sites
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ item }}"
    dest: "/etc/nginx/sites-enabled/{{ item }}"
    owner: root
    group: root
    state: link
  loop: "{{ sites.stdout_lines }}"

- name: Create www directories
  ansible.builtin.file:
    path: "{{ web_root }}/{{ item.server_dest }}"
    state: directory
    owner: "{{ ansible_web_user }}"
    group: "www-data"
    mode: "0750"
  loop: "{{ web_sources }}"

- name: Clone git repositories locally
  ansible.builtin.git:
    repo: "{{ item.source }}"
    dest: "tmp/{{ item.dest }}"
    version: main
  loop: "{{ web_sources }}"
  delegate_to: localhost

- name: Install npm dependencies locally
  ansible.builtin.command: npm install
  args:
    chdir: "tmp/{{ item.dest }}"
  changed_when: true
  loop: "{{ web_sources }}"
  when: item.quasar_build
  delegate_to: localhost
  register: result

- name: Build quasar repositories locally
  ansible.builtin.command: quasar build
  args:
    chdir: "tmp/{{ item.dest }}"
  changed_when: true
  loop: "{{ web_sources }}"
  when: item.quasar_build
  delegate_to: localhost
  register: result

- name: Copy quasar sources
  ansible.builtin.copy:
    src: "tmp/{{ item.dest }}/dist/spa/"
    dest: "{{ web_root }}/{{ item.server_dest }}"
    owner: "{{ ansible_web_user }}"
    group: www-data
    mode: "0640"
  loop: "{{ web_sources }}"
  when: item.quasar_build

- name: Copy non-quasar sources
  ansible.builtin.copy:
    src: "tmp/{{ item.dest }}/"
    dest: "{{ web_root }}/{{ item.server_dest }}"
    owner: "{{ ansible_web_user }}"
    group: www-data
    mode: "0640"
  loop: "{{ web_sources }}"
  when: not item.quasar_build

- name: Set Firewall rules
  block:
    - name: Allow ssh (22), http (80) & https (443)
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - 22
        - 80
        - 443

    - name: Enable Firewall and block traffic by default
      community.general.ufw:
        default: reject
        state: enabled

    - name: Enable and start ufw
      ansible.builtin.service:
        name: ufw
        state: started
        enabled: true
