---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - wireguard
    update_cache: yes

- name: Check if private key exists
  stat:
    path: /etc/wireguard/private.key
  register: stat_result

- name: Generate Private-Key
  ansible.builtin.shell:
    cmd: wg genkey | tee /etc/wireguard/private.key
  register: private_key
  when: not stat_result.stat.exists

- name: Get Private-Key
  ansible.builtin.shell:
    cmd: cat /etc/wireguard/private.key
  register: private_key
  when: stat_result.stat.exists

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /etc/wireguard/private.key
    owner: root
    group: root
    mode: "0600"

- name: Check if public key exists
  stat:
    path: /etc/wireguard/public.key
  register: stat_result

- name: Generate Public-Key
  ansible.builtin.shell:
    cmd: cat /etc/wireguard/private.key | wg pubkey | tee /etc/wireguard/public.key
  register: public_key
  when: not stat_result.stat.exists

- name: Get Public-Key
  ansible.builtin.shell:
    cmd: cat /etc/wireguard/private.key
  register: public_key
  when: stat_result.stat.exists

- name: Set privatekey to ansible variable
  ansible.builtin.set_fact:
    wireguard_server_private_key: "{{ private_key.stdout }}"
    wireguard_server_public_key: "{{ public_key.stdout }}"

- name: Create wg0.conf
  ansible.builtin.template:
    src: templates/wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: "0600"
